### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by AlainQ** [bleikamp/processing#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [processing](https://github.com/bleikamp/processing) package, v0.4.0

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904:15)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:554:26)
  at Object.module.exports.Processing.saveSketch (/Users/mimmvo/.atom/packages/processing/lib/processing.coffee:11:11)
  at Object.module.exports.Processing.runSketch (/Users/mimmvo/.atom/packages/processing/lib/processing.coffee:28:6)
  at atom-workspace.atom.commands.add.processing:run (/Users/mimmvo/.atom/packages/processing/lib/processing.coffee:7:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:78:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:151:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -2:31.9 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:37.8 editor:newline (atom-text-editor.editor.is-focused)
     -1:27.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:25.4 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:17.5 core:move-right (atom-text-editor.editor.is-focused)
     -1:13.7 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:10.2 core:backspace (atom-text-editor.editor.is-focused)
     -1:01.4 core:move-right (atom-text-editor.editor.is-focused)
     -0:57.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:46.9 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:44.4 core:move-left (atom-text-editor.editor.is-focused)
     -0:36.9 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "language-mustache"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.0
atom-python-debugger, v0.2.2
color-picker, v1.6.0
dart-tools, v0.8.9
javascript-snippets, v1.0.0
language-dart, v0.1.1
language-python-django-templates, v0.1.0
linter, v0.12.0
linter-dartanalyzer, v0.3.1
linter-pylint, v0.2.1
minimap, v4.7.6
processing, v0.4.0
processing-language, v0.1.0
script, v2.19.0

# Dev
No dev packages
```

**Comment by bleikamp** [comment]
Fixed in https://github.com/bleikamp/processing/commit/5d0059667d6d0b208a91be513b597987430e5f6a
